### PR TITLE
Adds missing link to Go text/template pkg

### PR DESCRIPTION
**Pull request by alexandrealvino**
Adds missing link in documentation

### CODE REVIEW

**Review by azdagron — DISMISSED** [review]
Thank you @alexandrealvino !

**Comment by azdagron** [comment]
Would you mind adding a DCO signoff to your commit? That is required for all contributions to the SPIFFE projects. See the failed action for details.

**Comment by alexandrealvino** [comment]
> 

Sorry about the delay, I had no power yesterday.

**Comment by azdagron** [comment]
> Sorry about the delay, I had no power yesterday.

Yikes, sorry to hear that! And no worries! Glad to see you have power back!

**Review by azdagron — APPROVED** [review]

**Pull request merged**
