### PR TITLE
Propose graduation to pre-prod maturity phase

### PR DESCRIPTION
**Pull request by azdagron**
I propose that we move this project to the pre-prod maturity level. I have been over the qualifications and believe that this project now meets the minimum bar.

@spiffe/ssc can you please review and take this move under consideration? I'm happy to provide links or answer questions.

### CODE REVIEW

**Comment by ajessup** [comment]
LGTM

**Comment by amoore877** [comment]
what's the hack folder for? https://github.com/spiffe/spire-controller-manager/blob/main/hack/boilerplate.go.txt . Something misbehaving for licensing / github?

**Comment by azdagron** [comment]
The hack folder is a boilerplate folder created and used by the kubebuilder tooling. It contains a copyright file that it adds to all of the generated code files. It seems to be a convention adopted by various [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/hack) related projects. I'm not quite sure what the intended use is for but regardless need it for kubebuilder tooling to function.

**Comment by amoore877** [comment]
> It seems to be a convention adopted by various [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/hack) related projects. I'm not quite sure what the intended use is for but regardless need it for kubebuilder tooling to function.

Ubiquitous hacks. The ultimate sign of project maturity 😄 

Everything else looks good to me for preprod 🎉

**Pull request merged**
