### PR TITLE
Bump Go to 1.19.5-alpine for docker build

### LINKED ISSUE #42: Use alpine-based Golang builder image, so that the environment matches the other SPIRE components
While not required, it might cause less confusion and be easier to maintain if all SPIRE components used the same environment (libc or musl). For this reason, we should consider changing the builder image to an Alpine-based image.

### PR DESCRIPTION
**Pull request by marcofranssen**
Switched to alpine as we will have same like we will do for spiffe-csi and spire images. Also see #51 

Supercedes and closes #46
fixes #42

### CODE REVIEW

**Comment by azdagron** [comment]
Should we move to the latest (go1.19.5 was released recently)?

**Comment by marcofranssen** [comment]
> Should we move to the latest (go1.19.5 was released recently)?

Definitely, I'm running behind, should have double checked.

**Comment by faisal-memon** [comment]
@marcofranssen Can you add the fixes https://github.com/spiffe/spire-controller-manager/issues/42 tag to link the issue?

**Comment by marcofranssen** [comment]
> @marcofranssen Can you add the fixes #42 tag to link the issue?

Done.

**Review by azdagron — APPROVED** [review]

**Comment by keeganwitt** [comment]
The makefile currently requires Bash. Should this be changed also?

**Pull request merged**
